language: python

branches:
  only:
  - /./       # Matches all the branches
  - gh-pages  # Explicitly allow gh-pages

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - git config user.name "Astrobot"
  - git config user.email "tom@chi-squared.org"

install:
  - pip install pyyaml

script:
  - python parse_entries.py
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 && $TRAVIS_BRANCH == "gh-pages" ]]; then
      git checkout gh-pages;
      git add database.json;
      git commit -m "Updated database.json";
      git push -f -q https://astrobot:$GITHUB_API_KEY@github.com/astrofrog/acknowledgment-generator gh-pages >& /dev/null;
    fi
